import Head from 'next/head';
import Navbar from '@/components/navbar/navbar';

const Blog = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
    </>
  );
};

export default Blog;
