import Head from 'next/head';
import Navbar from '@/components/navbar/navbar';
import EmailFrom from '@/components/emailForm/emailForm';
import styles from '@/styles/pages/chrome-extension.module.scss';
import StepsSection from '@/components/stepsSection/stepsSection';
import StoresSection from '@/components/storesSection/storesSection';

const ChromeExtension = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <div className={styles.container}>
        <div className={styles.contentWrapper}>
          <EmailFrom />
          <StepsSection />
        </div>
      </div>
      <StoresSection />
    </>
  );
};

export default ChromeExtension;
